[tasks.build]
run = "cargo build --workspace --all-features --all-targets --release"
description = "Build the project"
alias = "b"

[tasks.run]
alias = "r"
run = "cargo run --bin xoswap"
description = "Run the application"

[tools]
"cargo:cargo-llvm-cov" = "latest"
"cargo:cargo-nextest" = "latest"
"cargo:convco" = "latest"
dprint = "latest"
pkl = "latest"
rust = "latest"
hk = "latest"
