name: main

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  changed-files:
    runs-on: ubuntu-latest
    outputs:
      any_rs_changed: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - uses: actions/checkout@v4
      - uses: tj-actions/changed-files@v44
        id: changed-files
        with:
          files: |
            .github/workflows/main.yml
            src/**/*.rs
            Cargo.toml
            Cargo.lock

  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jdx/mise-action@v2
        with:
          mise_toml: |
            [tasks]
            "check:format" = { run = "dprint fmt" }
            "check:lint" = {run = "cargo clippy --all-targets --all-features --workspace"}
            check = { depends = "check:*"}
            [tools]
            dprint = "latest"
            rust = { version = "latest", profile = "minimal" }
      - name: Get toolchain version
        id: toolchain
        run: echo "toolchain=$(rustup show active-toolchain | awk '{print $1}')" >> $GITHUB_OUTPUT
      - name: Install rustfmt and clippy
        env:
          toolchain: ${{ steps.toolchain.outputs.toolchain }}
        run: |
          rustup update $toolchain
          rustup component add rustfmt clippy --toolchain $toolchain
      - run: mise r check
